idiomas = {
_("afar"): "aa",
_("abjasio"): "ab",
_("achenés"): "ace",
_("acholi"): "ach",
_("afrikáans"): "af",
_("twi"): "ak",
_("alur"): "alz",
_("amhárico"): "am",
_("árabe"): "ar",
_("asamés"): "as",
_("avar"): "av",
_("avadhi"): "awa",
_("aimara"): "ay",
_("azerí"): "az",
_("baskir"): "ba",
_("baluchí"): "bal",
_("balinés"): "ban",
_("batak toba"): "bbc",
_("baoulé"): "bci",
_("bielorruso"): "be",
_("bemba"): "bem",
_("tamazight (tifinag)"): "ber",
_("tamazight (latino)"): "ber-Latn",
_("betawi"): "bew",
_("rbúlgaro"): "bg",
_("bhoyapurí"): "bho",
_("bikol"): "bik",
_("bambara"): "bm",
_("n'ko"): "bm-Nkoo",
_("bengalí"): "bn",
_("tibetano"): "bo",
_("bretón"): "br",
_("bosnio"): "bs",
_("batak simalungun"): "bts",
_("batak karo"): "btx",
_("buriato"): "bua",
_("catalán"): "ca",
_("checheno"): "ce",
_("cebuano"): "ceb",
_("kiga"): "cgg",
_("chamorro"): "ch",
_("trukés"): "chk",
_("marí de las praderas"): "chm",
_("kurdo (sorani)"): "ckb",
_("hakha chin"): "cnh",
_("corso"): "co",
_("tártaro de Crimea (cirílico)"): "crh",
_("tártaro de Crimea (latino)"): "crh-Latn",
_("criollo seychellense"): "crs",
_("checo"): "cs",
_("chuvasio"): "cv",
_("galés"): "cy",
_("danés"): "da",
_("alemán"): "de",
_("dinka"): "din",
_("dogri"): "doi",
_("ndombe"): "dov",
_("divehi"): "dv",
_("diula"): "dyu",
_("dzongkha"): "dz",
_("ewé"): "ee",
_("griego"): "el",
_("inglés"): "en",
_("esperanto"): "eo",
_("español"): "es",
_("estonio"): "et",
_("euskera"): "eu",
_("persa"): "fa",
_("darí"): "fa-AF",
_("fulani"): "ff",
_("finlandés"): "fi",
_("fiyiano"): "fj",
_("feroés"): "fo",
_("fon"): "fon",
_("francés"): "fr",
_("francés (Canadá)"): "fr-CA",
_("friulano"): "fur",
_("frisio"): "fy",
_("irlandés"): "ga",
_("ga"): "gaa",
_("gaélico escocés"): "gd",
_("gallego"): "gl",
_("guaraní"): "gn",
_("konkaní"): "gom",
_("gujarati"): "gu",
_("manés"): "gv",
_("hausa"): "ha",
_("hawaiano"): "haw",
_("hebreo"): "he",
_("hindi"): "hi",
_("hiligaynon"): "hil",
_("hmong"): "hmn",
_("croata"): "hr",
_("hunsrik"): "hrx",
_("criollo haitiano"): "ht",
_("húngaro"): "hu",
_("armenio"): "hy",
_("iban"): "iba",
_("indonesio"): "id",
_("igbo"): "ig",
_("ilocano"): "ilo",
_("islandés"): "is",
_("italiano"): "it",
_("inuktut (silabario)"): "iu",
_("inuktut (latino)"): "iu-Latn",
_("japonés"): "ja",
_("patois jamaiquino"): "jam",
_("javanés"): "jv",
_("georgiano"): "ka",
_("jingpo"): "kac",
_("quekchí"): "kek",
_("kikongo"): "kg",
_("khasi"): "kha",
_("kazajo"): "kk",
_("kalaallisut"): "kl",
_("camboyano"): "km",
_("canarés"): "kn",
_("coreano"): "ko",
_("kanuri"): "kr",
_("krio"): "kri",
_("kituba"): "ktu",
_("kurdo (kurmanyi)"): "ku",
_("komi"): "kv",
_("kirguís"): "ky",
_("latín"): "la",
_("luxemburgués"): "lb",
_("luganda"): "lg",
_("limburgués"): "li",
_("ligur"): "lij",
_("lombardo"): "lmo",
_("lingala"): "ln",
_("lao"): "lo",
_("lituano"): "lt",
_("latgaliano"): "ltg",
_("chiluba"): "lua",
_("luo"): "luo",
_("mizo"): "lus",
_("letón"): "lv",
_("madurés"): "mad",
_("maithili"): "mai",
_("makassar"): "mak",
_("mam"): "mam",
_("criollo mauriciano"): "mfe",
_("malgache"): "mg",
_("marshalés"): "mh",
_("maorí"): "mi",
_("minangkabau"): "min",
_("macedonio"): "mk",
_("malayalam"): "ml",
_("mongol"): "mn",
_("meiteilon (manipurí)"): "mni-Mtei",
_("maratí"): "mr",
_("malayo"): "ms",
_("malayo (jawi)"): "ms-Arab",
_("maltés"): "mt",
_("marwari"): "mwr",
_("birmano"): "my",
_("ndau"): "ndc-ZW",
_("nepalí"): "ne",
_("nepalbhasa (newarí)"): "new",
_("náhuatl (Huasteca oriental)"): "nhe",
_("neerlandés"): "nl",
_("noruego"): "no",
_("ndebele meridional"): "nr",
_("sepedi"): "nso",
_("nuer"): "nus",
_("chichewa"): "ny",
_("occitano"): "oc",
_("oromo"): "om",
_("odia (oriya)"): "or",
_("osético"): "os",
_("panyabí (gurmukhi)"): "pa",
_("panyabí (shahmukhi)"): "pa-Arab",
_("pangasinán"): "pag",
_("pampango"): "pam",
_("papiamento"): "pap",
_("polaco"): "pl",
_("pastún"): "ps",
_("portugués (Brasil)"): "pt",
_("portugués (Portugal)"): "pt-PT",
_("quechua"): "qu",
_("kirundi"): "rn",
_("rumano"): "ro",
_("romaní"): "rom",
_("ruso"): "ru",
_("kinyarwanda"): "rw",
_("sánscrito"): "sa",
_("yakuto"): "sah",
_("santalí (ol chiki)"): "sat",
_("santalí (latino)"): "sat-Latn",
_("siciliano"): "scn",
_("sindhi"): "sd",
_("sami septentrional"): "se",
_("sango"): "sg",
_("shan"): "shn",
_("cingalés"): "si",
_("eslovaco"): "sk",
_("esloveno"): "sl",
_("samoano"): "sm",
_("shona"): "sn",
_("somalí"): "so",
_("albanés"): "sq",
_("serbio"): "sr",
_("suazi"): "ss",
_("sesoto"): "st",
_("sundanés"): "su",
_("susu"): "sus",
_("sueco"): "sv",
_("suajili"): "sw",
_("silesio"): "szl",
_("tamil"): "ta",
_("tulu"): "tcy",
_("telugu"): "te",
_("tetun"): "tet",
_("tayiko"): "tg",
_("tailandés"): "th",
_("tigrinya"): "ti",
_("tiv"): "tiv",
_("turkmeno"): "tk",
_("filipino"): "tl",
_("setsuana"): "tn",
_("tongano"): "to",
_("tok pisin"): "tpi",
_("turco"): "tr",
_("kokborok"): "trp",
_("tsonga"): "ts",
_("tártaro"): "tt",
_("tumbuka"): "tum",
_("tahitiano"): "ty",
_("tuviniano"): "tyv",
_("udmurto"): "udm",
_("uigur"): "ug",
_("ucraniano"): "uk",
_("urdu"): "ur",
_("uzbeco"): "uz",
_("venda"): "ve",
_("véneto"): "vec",
_("vietnamita"): "vi",
_("samareño"): "war",
_("wólof"): "wo",
_("xhosa"): "xh",
_("yidis"): "yi",
_("yoruba"): "yo",
_("maya yucateco"): "yua",
_("cantonés"): "yue",
_("zapoteco"): "zap",
_("Chino"): "zh-CN",
_("zulú"): "zu",
}
idiomas_naturales=list(idiomas.keys())

