idiomas = {
_("Alemán"): "de",
_("Árabe"): "ar",
_("Catalán"): "ca",
_("Corso"): "co",
_("Criollo haitiano"): "ht",
_("Croata"): "hr",
_("Español"): "es",
_("Esperanto"): "eo",
_("Euskera"): "eu",
_("Filipino (Tagalo)"): "tl",
_("Finés"): "fi",
_("Francés"): "fr",
_("Gallego"): "gl",
_("Griego"): "el",
_("Holandés"): "nl",
_("Hindi"): "hi",
_("Indonesio"): "id",
_("Inglés"): "en",
_("Italiano"): "it",
_("Japonés"): "ja",
_("Latín"): "la",
_("Maltés"): "mt",
_("Portugués"): "pt",
_("Rumano"): "ro",
_("Ruso"): "ru",
_("Servio"): "sr",
_("Sueco"): "sv",
_("Turco"): "tr",
_("Ucraniano"): "uk",
}
idiomas_naturales=list(idiomas.keys())

