idiomas = {
"Alemán": "de",
"Árabe": "ar",
"Catalán": "ca",
"Corso": "co",
"Criollo haitiano": "ht",
"Croata": "hr",
"Español": "es",
"Esperanto": "eo",
"Euskera": "eu",
"Filipino (Tagalo)": "tl",
"Finés": "fi",
"Francés": "fr",
"Gallego": "gl",
"Griego": "el",
"Holandés": "nl",
"Hindi": "hi",
"Indonesio": "id",
"Inglés": "en",
"Italiano": "it",
"Japonés": "ja",
"Latín": "la",
"Maltés": "mt",
"Portugués": "pt",
"Rumano": "ro",
"Ruso": "ru",
"Servio": "sr",
"Turco": "tr",
"Ucraniano": "uk",
}
idiomas_naturales=list(idiomas.keys())

